// online-store/src/components/Header.tsx
import React from 'react';
import './Header.css';
import Search from './Search';
import Cart from './Cart';

const Header = () => {
  return (
    <header>
      <div className="logo">
        <a href="#">VGS</a>
      </div>
      <Search />
      <Cart />
    </header>
  );
}

export default Header;

// online-store/src/app/components/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  @Input() color?: string;

  constructor() { }

  ngOnInit(): void { }

}

<header [ngStyle]="{'color': color}">
  <div class="logo">
    <a href="#">VGS</a>
  </div>
  <app-search></app-search>
  <app-cart></app-cart>
</header>
