// online-store/src/app/components/product/product.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from 'src/app/Product';
import { ProductsService } from 'src/app/services/products.service';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.scss']
})
export class ProductComponent implements OnInit {
  products: Product[] = this.productsService.getProducts();

  constructor(private productsService: ProductsService) { }

  ngOnInit(): void {
  }

}

<div class="product" *ngFor="let product of products" id="product{{ product.id }}">
  <div class="product-image">
    <img src="{{ product.image }}" alt="" />
  </div>
  <div class="product-name">
    {{ product.name }}
  </div>
  <div class="product-year">
    {{ product.year }}
  </div>
  <div class="product-platform">
    {{ product.platform }}
  </div>
  <div class="product-brand">
    {{ product.brand }}
  </div>
  <div class="product-popular">
    {{ product.popular }}
  </div>
  <div class="product-quantity">
    {{ product.quantity }}
  </div>
  <button class="product-add-to-cart">Add to cart</button>
</div>

// online-store/src/components/Product.tsx
import React from 'react';

const Product = () => {
  return (
    <div className="product">
      <div className="product-image">
        <img src="./assets/images/products/{{ product.image }}" width="200" alt="" />
      </div>
      <div className="product-name">
        Name:
      </div>
      <div className="product-year">
        Year: 
      </div>
      <div className="product-platform">
        Platform: 
      </div>
      <div className="product-brand">
        Brand: 
      </div>
      <div className="product-popular">
        Popular: 
      </div>
      <div className="product-quantity">
        Quantity: 
      </div>
      <button className="product-add-to-cart">Add to cart</button>
    </div>
  );
}

export default Product;
